export const NEXT_PUBLIC_APP_URL = process.env.NEXT_PUBLIC_APP_URL!;

export const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!;
export const EQUIPE_ID = process.env.NEXT_PUBLIC_APPWRITE_EQUIPE_ID!;
export const CONTRATANTES_ID =
  process.env.NEXT_PUBLIC_APPWRITE_CONTRATANTES_ID!;
export const SHOWS_ID = process.env.NEXT_PUBLIC_APPWRITE_SHOWS_ID!;
export const FATURAMENTOS_ID =
  process.env.NEXT_PUBLIC_APPWRITE_FATURAMENTOS_ID!;
export const LOCAIS_ID = process.env.NEXT_PUBLIC_APPWRITE_LOCAIS_ID!;
export const TIPOS_ID = process.env.NEXT_PUBLIC_APPWRITE_TIPOS_ID!;
export const USUARIOS_ID = process.env.NEXT_PUBLIC_APPWRITE_USUARIOS_ID!;
export const PROJETOS_ID = process.env.NEXT_PUBLIC_APPWRITE_PROJETOS_ID!;
export const PROJETOS_FINANCAS_ID =
  process.env.NEXT_PUBLIC_APPWRITE_PROJETOS_FINANCAS_ID!;
export const PROJETOS_MENSAGENS_ID =
  process.env.NEXT_PUBLIC_APPWRITE_PROJETOS_MENSAGENS_ID!;
export const PROJETOS_CATEGORIAS_ID =
  process.env.NEXT_PUBLIC_APPWRITE_PROJETOS_CATEGORIAS_ID!;
export const USER_PLANS_ID = process.env.NEXT_PUBLIC_APPWRITE_USER_PLANS_ID!;

export const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID!;
export const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET!;

export const STRIPE_PUBLISHABLE_KEY =
  process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY!;
export const STRIPE_SECRET_KEY = process.env.STRIPE_SECRET_KEY!;
export const STRIPE_CUSTOMER_PORTAL_URL =
  process.env.STRIPE_CUSTOMER_PORTAL_URL!;

export const STRIPE_PRODUCT_ID = process.env.STRIPE_PRODUCT_ID!;
export const STRIPE_TRIAL_PRICE_ID = process.env.STRIPE_TRIAL_PRICE_ID!;
export const STRIPE_MONTHLY_PRICE_ID = process.env.STRIPE_MONTHLY_PRICE_ID!;
export const STRIPE_YEARLY_PRICE_ID = process.env.STRIPE_YEARLY_PRICE_ID!;
